export const actionTypes = {
    FETCH_FILTERED_CARDS_COMPLETED: 'FETCH_FILTERED_CARDS_COMPLETED',
    FETCH_CARD_COMPLETED: 'FETCH_CARD_COMPLETED',
    UPDATE_CARD_SEARCH_TERMS: 'UPDATE_CARD_SEARCH_TERMS',
    FETCH_FILTERED_SETS_COMPLETED: 'FETCH_FILTERED_SETS_COMPLETED',
    FETCH_CARD_SYMBOLS_COMPLETED: 'FETCH_CARD_SYMBOLS_COMPLETED'
  };